package com.kernelpack.boot

/**
 * LZ4 解码的交叉验证向量 —— **由 Python 侧生成，请勿手改**。
 *
 * 生成方式：`ghostlock5x/tests/` 下的脚本从**真实 boot.img**（6.1.145 内核，
 * lz4_legacy 压缩）截取块数据，并用已验证的 Python 解码器算出期望输出。
 * Kotlin 侧只要解出同样的结果，就说明移植没有语义偏差。
 *
 * 真实向量只内嵌"压缩前缀 + 期望 sha256"，避免把 85 KB 的期望输出塞进源码。
 */
internal object Lz4Vectors {

    /** 真实 boot.img 第一个 lz4 块的压缩前缀（1536 字节）。 */
    const val REAL_COMPRESSED_B64 =
        "lU1aQPrL6HIUAAEAIE4CBgAvCgABAAv5AEFSTWRAAAAAUEUAAGSqAhwA8QCgAAYCCwICFAAACQIAAEQUAHZcgNABAAABJgAADAAVAgoAGgCAAAISABwKGwAPAQAELwYAAQAfUS50ZXh0CgATCXAALAkCbwCRIAAAYC5kYXRhDgAQRJIAQgIA2ikIAAcBAI9AAADAHyAD1QQA////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////oPBdImpX8z8jA9X9e7up+QsA+fhfAqn2VwOp9E8Eqf0DAJFoBwHQFKFA+ZMyAJHgAxOqQ+8elBUkABK/7g9xyAQAVPYDACqUQgCRdwcB0PkFAfA5cymRGEE41QsAABS9G0KU4LpD+eEDFSptAQWUQABAM+8elDQAAUQAcPIPcaICAFSIAPAp4AMWKuEDFKqy7h6U3z8D1b8+AHEo/v9UvzkD1QgTQLkIBQARCBMAuYjQONUWaTm4CAtA+QgFAPEUAEDA/P9UEAD3GKj8/7Xj//8X9E9EqfZXQ6n4X0Kp+QtA+f17xai/IwPVwANf1kjQPPQAYL6p8wsA+egAQCUAABSIAPMCE8w41Z8/A9Vodh4SH/EPcWCgAIBofkCSKMwY1RABAKAA8g3hAxMqAOlD+TcBBZRAAQA0CBcB8Al5SzlpAQA2MABhDVOIAAA1OAAwyxjVNAAR84wAFcKMAMApAIBSIKoAkADcLZFQAP8QCXkLOeOCApQAACHU7///F6gZAdAINUP5aPs/NgjJOMwBDi4JzCQAAMwAEAo8APQAAQrr6H+AUhMBiZrJ//8X0AAAmADyAdr//xfo//8XAAAAAAxnQKUcARG/AAK14AMfKn2pApT9e8G4AB8AAQD//////73wAf9DBdH/YyCL4GMgy4AAcDcIAPAB/2MgyxoCABQgAmg2YNAb1RAA8CEAQTjVAARAkQCAApEBCACpYQUBsCGgApGC0DjVIWhi+OIDAKrgAwCRPxBAkUEIQKlYAP8BqQYAFAD+ZzfPCAAUBgIAFIAAGR8VgAAwE86AAF+vCAAUAYAAHB8QgAAwE/OAAG+PCAAU/AGAABsfC4AAMCIYB4AAX28IABT3gAAcHwaAADATPYAAX08IABTygAAcHwGAADATYoAAXy8IABTtgAAcL/wBgAAvE4eAAF8PCAAU6IAAHB/3gAAwE6yAAF/vBwAU44AABJADAAAUftA71X9oAA+MAASA7wEAFEDQG9UQAACQAMBgBQHQH4AMkYDQONUwADFA0DscAJEfzHTygR0AVP8oAD471eF0AA+AACIvOQKAABgWGYAALysCgAAzH4OAABkWFYAAH3WAADQfzYAAGRYRgAAfv4AAEI8CAAAU/gMfqnwABS8YA3wAFyahDXwALgoDfAAPgAAhH2OAABkWCYAAH1WAADQfroAAGRYFgAAfoIAANB/5gAAZFgGAAB/rgAAUACwAAHwA8FHgBwCp4g8BqeQXAqnmHwOp6CcEqeovBansNwap7j8HqfBHCKnyTwmp9FcKqfZfC6n4Zwyp+m8Nqfx3Dqn1QwWRHEE41TZAONUXQDjV/lcPqf1bE6n9wwSRdRkAlPZfEKmoAIAAQAWR4H8A+agEMbP9QegOD3gARRNXeAAAbACPavhBlBIEABRsAEUXPGwAb3f4QZT3A2wARxchbABfZPhBlNxsAEgXBmwAX1H4QZTBbABIJusYbABfPvhBlKZsAEgX0GwAX8v4QZSLbABI"

    /** 上面前缀解码后的 sha256（Python 侧算出）。 */
    const val REAL_EXPECTED_SHA256 = "11bdf0390da9a385ce06e9c47acaa401d31d019aaaa544e9f3852a6efae01c07"

    const val REAL_EXPECTED_LENGTH = 70496

    /** 合成 A：字面量 + **重叠匹配**（offset=4 < 匹配长度，必须逐字节复制）。 */
    const val SYNTH_A_COMPRESSED_B64 = "SEFCQ0QEAA=="
    const val SYNTH_A_EXPECTED_B64 = "QUJDREFCQ0RBQkNEQUJDRA=="

    /** 合成 B：**超长匹配**（走 15 + 扩展字节路径）。 */
    const val SYNTH_B_COMPRESSED_B64 = "H1gBAPo="
    const val SYNTH_B_EXPECTED_B64 = "WFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhY"

    /** 合成 C：**多 sequence 串联**（字面量→匹配→字面量）。 */
    const val SYNTH_C_COMPRESSED_B64 = "yEhFTExPLVdPUkxELQwAgFRBSUxUQUlM"
    const val SYNTH_C_EXPECTED_B64 = "SEVMTE8tV09STEQtSEVMTE8tV09STEQtVEFJTFRBSUw="
}
