package com.kernelpack.export

import com.kernelpack.Hex
import com.kernelpack.model.OffsetEntry
import com.kernelpack.model.ResolveSource
import com.kernelpack.model.TargetProfile

/**
 * 导出**可以直接替换旧 `target.h`** 的 C 头文件。
 *
 * 这是"适配性高、能与其他项目合并"的关键出口：任何用 `-DTARGET_CONFIG_H=...`
 * 编译 preload.so 的工程（包括原始的 CVE-2026-43499 仓库）都能直接吃这份头文件重新编译，
 * 不需要改动一行 C 代码。
 */
object TargetHeaderWriter {

    fun write(profile: TargetProfile, guard: String = "OFFSET_H"): String = buildString {
        appendLine("#ifndef $guard")
        appendLine("#define $guard")
        appendLine()
        appendLine("/*")
        appendLine(" * Auto-generated by kernelpack (Kotlin boot.img offset packer); do not edit by hand.")
        appendLine(" * Kernel     : ${profile.versionNumber} (${profile.architecture})")
        appendLine(" * Variant    : ${profile.variantLabel}")
        appendLine(" * Image base : ${Hex.u64(profile.imageBase)}")
        appendLine(" *")
        appendLine(" * 符号类偏移由 boot.img 的 kallsyms 解析得到（来源标注见每行注释）；")
        appendLine(" * 结构体偏移为 ABI 档位常量，不随 boot.img 变化。")
        appendLine(" */")
        appendLine()
        appendLine("#define BUILD_VARIANT_LABEL \"${profile.variantLabel}\"")
        appendLine()
        appendLine("/* ---- Memory layout ---- */")
        appendLine("#define KIMAGE_TEXT_BASE ${Hex.u64(profile.imageBase)}ULL")
        for ((k, v) in profile.memoryLayout) {
            appendLine("#define $k ${Hex.u64(v)}ULL")
        }
        appendLine()
        appendLine("/* ---- Kernel symbols (image-relative offsets) ---- */")
        for ((k, e) in profile.offsets) {
            if (!e.resolved) {
                appendLine("/* #define ${k}_OFF  <未解析: ${e.detail}> */")
                continue
            }
            appendLine("#define ${k}_OFF ${Hex.u(e.offset!!)}ULL  /* ${sourceLabel(e)} */")
        }
        appendLine()
        appendLine("/* ---- 绝对地址形式（便于与旧 target.h 对拍） ---- */")
        for ((k, e) in profile.offsets) {
            if (!e.resolved) continue
            appendLine("#define $k (KIMAGE_TEXT_BASE + ${k}_OFF)")
        }
        appendLine()
        appendLine("/* ---- Struct / ABI offsets (来自 ABI 档位，与 boot.img 无关) ---- */")
        for ((k, v) in profile.structOffsets) {
            appendLine("#define $k ${Hex.u(v)}ULL")
        }
        appendLine()
        if (profile.unresolved.isNotEmpty()) {
            appendLine("/* 未解析项: ${profile.unresolved.joinToString(", ")} */")
            appendLine()
        }
        appendLine("#endif /* $guard */")
    }

    private fun sourceLabel(e: OffsetEntry): String = when (e.source) {
        ResolveSource.KALLSYMS -> "kallsyms"
        ResolveSource.KALLSYMS_DERIVED -> "kallsyms 推导"
        ResolveSource.IMAGE_READ -> "镜像读指针"
        ResolveSource.IMAGE_SCAN -> "镜像结构扫描"
        ResolveSource.BASELINE -> "沿用基线"
        ResolveSource.UNAVAILABLE -> "未解析"
    }
}
